# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-04 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_taskfile_is_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskfile',
            name='comment',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='taskfile',
            name='grade',
            field=models.IntegerField(default=0),
        ),
    ]
