# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 18:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20160708_0059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='leader',
            new_name='user',
        ),
    ]
