# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-05 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20160704_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='submit_time',
            field=models.DateTimeField(default='2016-01-01'),
        ),
        migrations.AddField(
            model_name='user',
            name='real_name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
