# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-05 10:43
from __future__ import unicode_literals

import app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20160705_1444'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('message', models.CharField(max_length=200)),
                ('courseid', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='pic',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AlterField(
            model_name='resource',
            name='server_path',
            field=models.FileField(upload_to=app.models.get_resource_path),
        ),
        migrations.AlterField(
            model_name='resource',
            name='submit_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='taskfile',
            name='submit_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='real_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AddField(
            model_name='chat',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User'),
        ),
    ]
