# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 07:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='submit_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 7, 5, 7, 5, 3, 826000, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='pic',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='real_name',
            field=models.CharField(default='realname', max_length=30),
            preserve_default=False,
        ),
    ]
