# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 02:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20160708_0301'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='end',
            field=models.IntegerField(default=1),
        ),
    ]
