# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-05 11:00
from __future__ import unicode_literals

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20160705_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskfile',
            name='server_path',
            field=models.FileField(default='/task', upload_to=app.models.get_task_file_path),
        ),
    ]
